name: Train Student Model
description: Trains a model on student features and saves it as a .pkl file.
inputs:
  - {name: features_path, type: String}
  - {name: model_output_path, type: String}
outputs:
  - {name: model_output_path, type: String}
implementation:
  container:
    image: docker.io/samyukthagudiya17/train_model:latest
    command:
      - python
      - train_model.py
    args:
      - --features_path
      - {inputValue: features_path}
      - --model_output_path
      - {outputPath: model_output_path}
