name: Train Model
description: Trains a student exam prediction model and saves it.
inputs:
  - name: features_path
    type: String
  - name: target_column
    type: String
outputs:
  - name: model_path
    type: String
implementation:
  container:
    image: docker.io/samyukthagudiya17/train_model:latest
    command: ["python", "train_model.py"]
    args:
      - "--features_path"
      - {inputValue: features_path}
      - "--target_column"
      - {inputValue: target_column}
      - "--model_path"
      - {outputPath: model_path}
