name: Train Model
description: Trains a RandomForest classifier on student features.
inputs:
  - {name: features_csv, type: CSV}
  - {name: label_column, type: String, default: 'label'}
outputs:
  - {name: model_output, type: Model}
implementation:
  container:
    image: samyukthagudiya17/train_model:latest
    command: [python, /app/train_model.py]
    args: [
      --features_csv, {inputPath: features_csv},
      --label_column, {inputValue: label_column},
      --model_output, {outputPath: model_output}
    ]
    volumeMounts:
      - {name: output-vol, mountPath: /mnt/output}
